language: c++
dist: trusty
cache:
  ccache: true
  directories:
   - cmake


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # more recent CMake

    packages:
    - cmake
    - gdb
    - gcc-4.9
    - g++-4.9
    - gcc-4.9-multilib
    - g++-4.9-multilib
    - gcc-multilib
    - g++-multilib
    - libedit2
    - libedit-dev
    - libcurl3:i386
    - ninja-build
    - build-essential

before_install:
  # cmake install
  # - if [ ! -e "cmake-3.8.1" ]; then
  #    wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz
  #    tar xf cmake-3.8.1.tar.gz
  #  fi

  - export PATH=$HOME/cmake/bin:$PATH

  - if ! [[ $(cmake --version | grep "3.8.1") ]]; then
        mkdir $HOME/cmake -p;
        wget https://cmake.org/files/v3.8/cmake-3.8.1.tar.gz;
        tar xf cmake-3.8.1.tar.gz;
        cd cmake-3.8.1;
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/cmake .;
        make -j4;
        make -j4 install;
        cmake --version;
    fi 

  - echo $PATH

  # LLVM + Polly clone
  - cd $HOME
  - git clone https://github.com/llvm-mirror/llvm.git
  - cd llvm/tools
  - git clone https://github.com/llvm-mirror/polly.git
  - cd ../../
  
  - mkdir llvm_build
  - cd llvm_build

script:
  - cmake --version
  - cmake ../llvm -GNinja -DPOLLY_ENABLE_GPGPU_CODEGEN=ON -DBUILD_SHARED_LIBS=ON
  - ninja libGPURuntime.so
  - ninja libLLVMAArch64AsmParser.dylib
  - ninja libLLVMAArch64AsmPrinter.dylib
  - ninja libLLVMAArch64CodeGen.dylib
  - ninja libLLVMAArch64Desc.dylib
  - ninja libLLVMAArch64Disassembler.dylib
  - ninja libLLVMAArch64Info.dylib
  - ninja libLLVMAArch64Utils.dylib
  - ninja libLLVMAMDGPUAsmParser.dylib
  - ninja libLLVMAMDGPUAsmPrinter.dylib
  - ninja libLLVMAMDGPUCodeGen.dylib
  - ninja libLLVMAMDGPUDesc.dylib
  - ninja libLLVMAMDGPUDisassembler.dylib
  - ninja libLLVMAMDGPUInfo.dylib
  - ninja libLLVMAMDGPUUtils.dylib
  - ninja libLLVMARMAsmParser.dylib
  - ninja libLLVMARMAsmPrinter.dylib
  - ninja libLLVMARMCodeGen.dylib
  - ninja libLLVMARMDesc.dylib
  - ninja libLLVMARMDisassembler.dylib
  - ninja libLLVMARMInfo.dylib
  - ninja libLLVMAnalysis.dylib
  - ninja libLLVMAsmParser.dylib
  - ninja libLLVMAsmPrinter.dylib
  - ninja libLLVMBPFAsmPrinter.dylib
  - ninja libLLVMBPFCodeGen.dylib
  - ninja libLLVMBPFDesc.dylib
  - ninja libLLVMBPFDisassembler.dylib
  - ninja libLLVMBPFInfo.dylib
  - ninja libLLVMBitReader.dylib
  - ninja libLLVMBitWriter.dylib
  - ninja libLLVMCodeGen.dylib
  - ninja libLLVMCore.dylib
  - ninja libLLVMCoroutines.dylib
  - ninja libLLVMCoverage.dylib
  - ninja libLLVMDebugInfoCodeView.dylib
  - ninja libLLVMDebugInfoDWARF.dylib
  - ninja libLLVMDebugInfoMSF.dylib
  - ninja libLLVMDebugInfoPDB.dylib
  - ninja libLLVMDemangle.dylib
  - ninja libLLVMExecutionEngine.dylib
  - ninja libLLVMFuzzer.a
  - ninja libLLVMFuzzerNoMain.a
  - ninja libLLVMGlobalISel.dylib
  - ninja libLLVMHexagonAsmParser.dylib
  - ninja libLLVMHexagonCodeGen.dylib
  - ninja libLLVMHexagonDesc.dylib
  - ninja libLLVMHexagonDisassembler.dylib
  - ninja libLLVMHexagonInfo.dylib
  - ninja libLLVMIRReader.dylib
  - ninja libLLVMInstCombine.dylib
  - ninja libLLVMInstrumentation.dylib
  - ninja libLLVMInterpreter.dylib
  - ninja libLLVMLTO.dylib
  - ninja libLLVMLanaiAsmParser.dylib
  - ninja libLLVMLanaiAsmPrinter.dylib
  - ninja libLLVMLanaiCodeGen.dylib
  - ninja libLLVMLanaiDesc.dylib
  - ninja libLLVMLanaiDisassembler.dylib
  - ninja libLLVMLanaiInfo.dylib
  - ninja libLLVMLibDriver.dylib
  - ninja libLLVMLineEditor.dylib
  - ninja libLLVMLinker.dylib
  - ninja libLLVMMC.dylib
  - ninja libLLVMMCDisassembler.dylib
  - ninja libLLVMMCJIT.dylib
  - ninja libLLVMMCParser.dylib
  - ninja libLLVMMIRParser.dylib
  - ninja libLLVMMSP430AsmPrinter.dylib
  - ninja libLLVMMSP430CodeGen.dylib
  - ninja libLLVMMSP430Desc.dylib
  - ninja libLLVMMSP430Info.dylib
  - ninja libLLVMMipsAsmParser.dylib
  - ninja libLLVMMipsAsmPrinter.dylib
  - ninja libLLVMMipsCodeGen.dylib
  - ninja libLLVMMipsDesc.dylib
  - ninja libLLVMMipsDisassembler.dylib
  - ninja libLLVMMipsInfo.dylib
  - ninja libLLVMNVPTXAsmPrinter.dylib
  - ninja libLLVMNVPTXCodeGen.dylib
  - ninja libLLVMNVPTXDesc.dylib
  - ninja libLLVMNVPTXInfo.dylib
  - ninja libLLVMObjCARCOpts.dylib
  - ninja libLLVMObject.dylib
  - ninja libLLVMObjectYAML.dylib
  - ninja libLLVMOption.dylib
  - ninja libLLVMOrcJIT.dylib
  - ninja libLLVMPasses.dylib
  - ninja libLLVMPowerPCAsmParser.dylib
  - ninja libLLVMPowerPCAsmPrinter.dylib
  - ninja libLLVMPowerPCCodeGen.dylib
  - ninja libLLVMPowerPCDesc.dylib
  - ninja libLLVMPowerPCDisassembler.dylib
  - ninja libLLVMPowerPCInfo.dylib
  - ninja libLLVMProfileData.dylib
  - ninja libLLVMRISCVCodeGen.dylib
  - ninja libLLVMRISCVDesc.dylib
  - ninja libLLVMRISCVInfo.dylib
  - ninja libLLVMRuntimeDyld.dylib
  - ninja libLLVMScalarOpts.dylib
  - ninja libLLVMSelectionDAG.dylib
  - ninja libLLVMSparcAsmParser.dylib
  - ninja libLLVMSparcAsmPrinter.dylib
  - ninja libLLVMSparcCodeGen.dylib
  - ninja libLLVMSparcDesc.dylib
  - ninja libLLVMSparcDisassembler.dylib
  - ninja libLLVMSparcInfo.dylib
  - ninja libLLVMSupport.dylib
  - ninja libLLVMSymbolize.dylib
  - ninja libLLVMSystemZAsmParser.dylib
  - ninja libLLVMSystemZAsmPrinter.dylib
  - ninja libLLVMSystemZCodeGen.dylib
  - ninja libLLVMSystemZDesc.dylib
  - ninja libLLVMSystemZDisassembler.dylib
  - ninja libLLVMSystemZInfo.dylib
  - ninja libLLVMTableGen.dylib
  - ninja libLLVMTarget.dylib
  - ninja libLLVMTransformUtils.dylib
  - ninja libLLVMVectorize.dylib
  - ninja libLLVMX86AsmParser.dylib
  - ninja libLLVMX86AsmPrinter.dylib
  - ninja libLLVMX86CodeGen.dylib
  - ninja libLLVMX86Desc.dylib
  - ninja libLLVMX86Disassembler.dylib
  - ninja libLLVMX86Info.dylib
  - ninja libLLVMX86Utils.dylib
  - ninja libLLVMXCoreAsmPrinter.dylib
  - ninja libLLVMXCoreCodeGen.dylib
  - ninja libLLVMXCoreDesc.dylib
  - ninja libLLVMXCoreDisassembler.dylib
  - ninja libLLVMXCoreInfo.dylib
  - ninja libLLVMXRay.dylib
  - ninja libLLVMipo.dylib
  - ninja libLTO.dylib
  - ninja libPolly.dylib
  - ninja libPollyISL.dylib
  - ninja libPollyPPCG.dylib
  - ninja opt
  - ninja check-polly
  

# NOTES:
# 1. spends more time `cmake`ing than anything else for the cmake bootstrap process
# 2. ccache = awesome
